# Generated by Django 6.0.4 on 2026-04-25 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da empresa"),
                ),
                (
                    "nif",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="NIF da empresa"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefone"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Morada")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário da empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HierarchyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Lower numbers represent higher hierarchy.",
                        verbose_name="Nível",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hierarchy_levels",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível de hierarquia",
                "verbose_name_plural": "Níveis de hierarquia",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Cargo")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="companies.hierarchylevel",
                        verbose_name="Nível de hierarquia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["hierarchy_level__level", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("OWNER", "Dono responsável"),
                            ("EMPLOYEE", "Funcionário"),
                            ("PARTNER", "Sócio"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de vínculo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="companies.role",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo com empresa",
                "verbose_name_plural": "Vínculos com empresas",
                "ordering": ["company", "person__full_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="hierarchylevel",
            constraint=models.UniqueConstraint(
                fields=("company", "level"), name="unique_hierarchy_level_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="hierarchylevel",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_hierarchy_name_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_role_name_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="companymembership",
            constraint=models.UniqueConstraint(
                fields=("company", "person"),
                name="unique_person_membership_per_company",
            ),
        ),
    ]
