# Generated by Django 6.0.4 on 2026-04-25 23:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nome do banco"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banks",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Saldo inicial",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_accounts",
                        to="finances.bank",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_accounts",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Titular",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta financeira",
                "verbose_name_plural": "Contas financeiras",
                "ordering": ["bank__name", "holder__full_name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("INCOME", "Entrada"), ("EXPENSE", "Saída")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Único"),
                            ("INSTALLMENT", "Parcelado"),
                            ("FIXED", "Fixo"),
                        ],
                        default="SINGLE",
                        max_length=20,
                        verbose_name="Recorrência",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de vencimento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Efetuada"),
                            ("OVERDUE", "Atrasada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "installment_group",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Grupo de parcelamento"
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número da parcela"
                    ),
                ),
                (
                    "installment_total",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total de parcelas"
                    ),
                ),
                (
                    "fixed_group",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Grupo fixo"
                    ),
                ),
                (
                    "is_imported",
                    models.BooleanField(default=False, verbose_name="Importado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="finances.financialaccount",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_movements",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento financeiro",
                "verbose_name_plural": "Movimentos financeiros",
                "ordering": ["-due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_transfers",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="finances.financialaccount",
                        verbose_name="Conta de destino",
                    ),
                ),
                (
                    "destination_movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_transfer",
                        to="finances.financialmovement",
                        verbose_name="Movimento de entrada",
                    ),
                ),
                (
                    "origin_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="finances.financialaccount",
                        verbose_name="Conta de origem",
                    ),
                ),
                (
                    "origin_movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_transfer",
                        to="finances.financialmovement",
                        verbose_name="Movimento de saída",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência financeira",
                "verbose_name_plural": "Transferências financeiras",
                "ordering": ["-due_date"],
            },
        ),
    ]
