# Generated by Django 6.0.4 on 2026-04-25 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("finances", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.UniqueConstraint(
                fields=("company", "bank", "holder"),
                name="unique_financial_account_per_company_bank_holder",
            ),
        ),
    ]
