# Generated by Django 6.0.4 on 2026-04-26 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finances",
            "0002_financialaccount_unique_financial_account_per_company_bank_holder",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="financialmovement",
            name="fixed_occurrence_month",
            field=models.DateField(
                blank=True, null=True, verbose_name="Mês da ocorrência fixa"
            ),
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="is_fixed_template",
            field=models.BooleanField(default=False, verbose_name="É modelo fixo"),
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="paid_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de efetivação"
            ),
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="parent_fixed_movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixed_occurrences",
                to="finances.financialmovement",
                verbose_name="Movimento fixo de origem",
            ),
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="payment_comment",
            field=models.TextField(blank=True, verbose_name="Comentário da efetivação"),
        ),
    ]
