# Generated by Django 6.0.4 on 2026-04-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_financialmovement_fixed_occurrence_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialmovement",
            name="external_reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Referência externa"
            ),
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="is_reconciled",
            field=models.BooleanField(default=False, verbose_name="Conciliado"),
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="reconciled_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_movements",
                to="finances.financialmovement",
                verbose_name="Conciliado com",
            ),
        ),
    ]
