# Generated by Django 6.0.4 on 2026-04-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("finances", "0004_financialmovement_external_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatementImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("external_reference", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IMPORTED", "Importado"),
                            ("MATCHED", "Conciliado"),
                            ("DUPLICATED", "Duplicado"),
                            ("INVALID", "Inválido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_line", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_imports",
                        to="finances.financialaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_imports",
                        to="companies.company",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="statement_entries",
                        to="finances.financialmovement",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
