# Generated by Django 6.0.4 on 2026-04-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("finances", "0005_bankstatementimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("INCOME", "Entrada"), ("EXPENSE", "Saída")],
                        max_length=20,
                        verbose_name="Tipo de movimentação",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Categoria")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_categories",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria financeira",
                "verbose_name_plural": "Categorias financeiras",
                "ordering": ["movement_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="finances.financialcategory",
                verbose_name="Categoria",
            ),
        ),
        migrations.CreateModel(
            name="FinancialSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Subcategoria")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="finances.financialcategory",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_subcategories",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoria financeira",
                "verbose_name_plural": "Subcategorias financeiras",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="finances.financialsubcategory",
                verbose_name="Subcategoria",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialcategory",
            constraint=models.UniqueConstraint(
                fields=("company", "movement_type", "name"),
                name="unique_financial_category_per_company_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsubcategory",
            constraint=models.UniqueConstraint(
                fields=("company", "category", "name"),
                name="unique_financial_subcategory_per_category",
            ),
        ),
    ]
