# Generated by Django 6.0.4 on 2026-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("finances", "0006_financialcategory_financialmovement_category_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bank",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_bank_name_per_company"
            ),
        ),
    ]
