# Generated by Django 6.0.4 on 2026-04-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0007_bank_unique_bank_name_per_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementimport",
            name="ai_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Confiança da IA",
            ),
        ),
        migrations.AddField(
            model_name="bankstatementimport",
            name="ai_reason",
            field=models.TextField(blank=True, verbose_name="Justificativa da IA"),
        ),
        migrations.AddField(
            model_name="bankstatementimport",
            name="suggested_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_statement_imports",
                to="finances.financialcategory",
                verbose_name="Categoria sugerida",
            ),
        ),
        migrations.AddField(
            model_name="bankstatementimport",
            name="suggested_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_statement_imports",
                to="finances.financialsubcategory",
                verbose_name="Subcategoria sugerida",
            ),
        ),
    ]
