# Generated by Django 6.0.4 on 2026-04-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0008_bankstatementimport_ai_confidence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankstatementimport",
            name="ai_confidence",
        ),
        migrations.RemoveField(
            model_name="bankstatementimport",
            name="ai_reason",
        ),
        migrations.AddField(
            model_name="bankstatementimport",
            name="categorization_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Confiança da categorização",
            ),
        ),
        migrations.AddField(
            model_name="bankstatementimport",
            name="categorization_reason",
            field=models.TextField(
                blank=True, verbose_name="Justificativa da categorização"
            ),
        ),
        migrations.AddField(
            model_name="bankstatementimport",
            name="categorization_source",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Origem da categorização"
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementimport",
            name="suggested_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statement_import_suggestions",
                to="finances.financialcategory",
                verbose_name="Categoria sugerida",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementimport",
            name="suggested_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statement_import_suggestions",
                to="finances.financialsubcategory",
                verbose_name="Subcategoria sugerida",
            ),
        ),
    ]
