# Generated by Django 6.0.4 on 2026-04-26 22:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        (
            "finances",
            "0010_alter_bank_options_alter_bankstatementimport_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                            ("AMEX", "American Express"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Bandeira",
                    ),
                ),
                (
                    "last_digits",
                    models.CharField(max_length=4, verbose_name="Final do cartão"),
                ),
                (
                    "limit",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Limite"
                    ),
                ),
                (
                    "closing_day",
                    models.PositiveSmallIntegerField(verbose_name="Dia de fecho"),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(verbose_name="Dia de vencimento"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_cards",
                        to="finances.financialaccount",
                        verbose_name="Conta de pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão de crédito",
                "verbose_name_plural": "Cartões de crédito",
                "ordering": ["brand", "last_digits"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("purchase_date", models.DateField(verbose_name="Data da compra")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor total"
                    ),
                ),
                (
                    "installments",
                    models.PositiveIntegerField(default=1, verbose_name="Parcelas"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="finances.creditcard",
                        verbose_name="Cartão",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_card_expenses",
                        to="finances.financialcategory",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_card_expenses",
                        to="finances.financialsubcategory",
                        verbose_name="Subcategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto de cartão",
                "verbose_name_plural": "Gastos de cartão",
                "ordering": ["-purchase_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_month", models.DateField(verbose_name="Mês de referência")),
                ("closing_date", models.DateField(verbose_name="Data de fecho")),
                ("due_date", models.DateField(verbose_name="Data de vencimento")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("PAID", "Efetuada"),
                            ("CANCELED", "Cancelada"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="finances.creditcard",
                        verbose_name="Cartão",
                    ),
                ),
                (
                    "payment_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_card_invoice",
                        to="finances.financialmovement",
                        verbose_name="Movimento financeiro da fatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura de cartão",
                "verbose_name_plural": "Faturas de cartão",
                "ordering": ["-reference_month"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(verbose_name="Número da parcela"),
                ),
                (
                    "installment_total",
                    models.PositiveIntegerField(verbose_name="Total de parcelas"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_card_installments",
                        to="finances.financialcategory",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_installments",
                        to="finances.creditcardexpense",
                        verbose_name="Gasto",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_card_installments",
                        to="finances.financialsubcategory",
                        verbose_name="Subcategoria",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="finances.creditcardinvoice",
                        verbose_name="Fatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela de cartão",
                "verbose_name_plural": "Parcelas de cartão",
                "ordering": ["invoice__reference_month", "installment_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="creditcard",
            constraint=models.UniqueConstraint(
                fields=("company", "payment_account", "last_digits"),
                name="unique_credit_card_per_account_last_digits",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditcardinvoice",
            constraint=models.UniqueConstraint(
                fields=("card", "reference_month"),
                name="unique_credit_card_invoice_per_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditcardinstallment",
            constraint=models.UniqueConstraint(
                fields=("expense", "installment_number"),
                name="unique_credit_card_expense_installment",
            ),
        ),
    ]
